version: '3.6'

services:
  app:
    image: craictech/alp-phpfpm-nginx:0.1.5
    volumes:
      - ./examples:/www
    ports:
      - "80:80"
    environment:
      SERVER_NAME: "localhost"
      SERVER_ROOT: "/www"
