version: '3.6'

services:
  app:
    image: rico/alp-s6-test:0.1.2
    volumes:
      - ./examples:/www
    ports:
      - "80:80"
    environment:
      SERVER_NAME: "localhost"
      SERVER_ROOT: "/www"
